### PR TITLE
setting yatspec output folder to target/yatspec

### PR DESCRIPTION
**Pull request by alfanse**
Hi tad,
Very grateful to you for doing this, I've been trying to remember how to render sequence diagrams in an A/T for ages.
Noticed the reports are being written to default location (java.io.tmpdir), this commit changes it to target/yatspec.
What I'm hoping todo is get the reports hosted on travis, so we can show them to people, without needing to run the build.
Incase travis doesn't do this for free, please consider using circle.ci it keeps the artifacts from the build. i.e.
https://79-28635373-gh.circle-artifacts.com/0/home/ubuntu/embers/embers-acceptance-tests/build/reports/acceptance/adf/embers/e2e/PuttingItAllTogetherTest.html

Regards
Alfanse

### CODE REVIEW

**Comment by theangrydev** [comment]
Hey, I'm glad someone found this useful.

This project was just me messing around a while ago to generate a diagram based on the runtime method invocations. It turned out to not be too useful in practice because real world call stacks tend to be huuuge!

Are you just using the standard sequence diagram feature of yatspec or did you find a use for the runtime `SequenceRecorder` bit too? If you only need hand-crafted diagrams then you can ignore all the code in this project related to the `SequenceRecorder`.

On my team at work, we generate sequence diagrams for HTTP interactions by listening to a Wiremock stub and adding the request/response data into the yatspec `CapturedInputAndOutputs` with keys like `Call from A to B` and values as rendered HTTP requests/responses. This turns out to be very handy when you have lots of interactions to visualise.

Oh and I'm not sure who/what "tad" is :)

**Comment by alfanse** [comment]
tad=TheAngryDev?

**Comment by theangrydev** [comment]
Ahh right

**Comment by alfanse** [comment]
Hi theangrydev,
I've recently touched down in HSBC and have noticed the Nexus here does not
have yatspec, but does have
Io.github.theangrydev:Yatspec-fluent v5.0.2
Io.github.theangrydev:Yatspec-zohhak-plugin v1.1.1
Yatpsec-extensions v8.2.2

As I'm interested in using a yatspec style bdd, what can you tell me about
these libs?
Example consumer would be lovely, but my searches in github.hsbc have drawn
blanks.

Any tips greatfully received,
A

On 5 Feb 2017 10:25 pm, "Liam Williams" <notifications@github.com> wrote:

Ahh right

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/theangrydev/yatspec-runtime-sequence-diagrams/pull/1#issuecomment-277555003>,
or mute the thread

**Comment by theangrydev** [comment]
I'll reply to this properly later if you need more guidance, but here are some quick pointers to begin with.

yatspec-fluent was renamed to https://github.com/theangrydev/fluent-bdd, you can find a usage example in the README.md. There is an optional module yatspec-extensions for that project that transitively depends on vanilla yatspec. Unfortunately if yatspec isn't in your Nexus then that won't be much use to you. However, you can use the core module of Fluent BDD to write tests in a fluent style. You won't get the nice rendered yatspec output though :(

yatspec-zohhak-plugin is a plugin for vanilla yatspec that integrates with https://github.com/piotrturski/zohhak in order to convert String types to other types when used in yatspec `@Table` tests. Again, this project depends on yatspec so is of no use to you if you can't pull in yatspec.

It's worth bothering Dan maybe via an issue on https://github.com/bodar/yatspec to see if he is open to publishing yatspec on maven central. Currently he just publishes to his own repository.

Hope this helps!

**Comment by theangrydev** [comment]
Oh and I guess HSBC won't have access to this but you could also try adding this to your pom.xml
```
<repository>
     <id>repo.bodar.com</id>
     <url>http://repo.bodar.com</url>
</repository>
```

After adding http://repo.bodar.com to your Nexus.

**Comment by alfanse** [comment]
Thanks tad.
So did you used to work in HSBC?

**Comment by theangrydev** [comment]
Nope, I'm currently at Sky. Libraries like yatspec and other Dan stack libraries are used quite heavily on some old systems here and we still use yatspec on my team for acceptance tests :)

**Pull request merged**
